### ISSUE TITLE
Help Popup module evolution

### ISSUE THREAD

**Issue by bealdav** [OCA/knowledge#103]
This PR https://github.com/OCA/web/pull/417
propose a way to aggregate help content by model or action

Help popup module
# Pros
- several modules can put their doc content on the same object with the same field
- end users can be see contextual doc of several modules
- end users can add/replace some parts of the doc
- documentation can be aggregated for a whole menu (Sales, Accounting ...) and be extended to the whole ERP.
# Cons / Todo
- help fields (which store content) are in ir.model and ir.act_window: easy but not fine for security rules ?
- no way to reuse customized parts of doc provided by endusers
- no use of qweb then doc inherits impossible: only add some parts.
- no interaction between modules in knowledge repos and this module (changes approval, etc.)

**Comment by max3903** [comment]
Related issues:
- #38 
- #39 
- https://github.com/OCA/website/issues/19
- https://github.com/OCA/web/tree/8.0/help_online

As discussed, I propose:
- to use document.page to store content
- your module (web_help in OCA/web) to have a relationship with window action or model and to display it in the backend
- website_help in OCA/website to display it on the website (as a public wiki)

**Comment by hbrunn** [comment]
I'm busy with `help_popup_document_page`, which should do most of the above

**Comment by SalahAdDin** [comment]
@hbrunn looks great!!!

**Comment by etobella** [comment]
Is this still relevant? @bealdav

**Comment by bealdav** [comment]
I never took time to port my initial module. I don't know if it so useful for a large public.

It's the problem with OCA we don't know who use our modules.
