### ISSUE TITLE
Redirect to main page, when accessing document from category

### ISSUE THREAD

**Issue by Auneor** [OCA/knowledge#117]
On a fresh install, after configuring Manage documents and Manage document pages (Wiki) 
We create a new page (for exemple page1)
We set a new category to this page (cat1)
We save.
We open page1
We click on the category cat1
Here we click on the Documents tab
We have the document page1, when we click on it, we are redirected to the main page instead of the document

**Comment by max3903** [comment]
Hello @MohammedAuneor 

I just tried on runbot and I am redirected to the page1 content. I don't see any problem here.

Please re-open if you think otherwise.
