### ISSUE TITLE
unported addon attachment_preview

### ISSUE THREAD

**Issue by MMstp** [OCA/knowledge#131]
Hi OCA developers,

I wanted to ask if you are planning to port the addon attachment_preview to version 10.0?
I was very satisfied with this addon in my odoo v8 and I would appreciate it when it's also available for my odoo v10.
Just let me know if & when you plan to release a v10, or if I have to search for an alternative addon.

Thank you in advance,
MM

**Comment by dreispt** [comment]
We have an Issue for each migration to keep track of ongoing work.
In this case you should check #72 and #105.

I can see that there is an ongoing migration to 9.0 here: #108
Maybe you can help it to get merged.
Chances are that the effort of moving from 9.0 to 10.0 is small.

**Comment by MMstp** [comment]
Ok. Thank you for the reply!
I just have Odoo 10, so I'm not sure if I can help getting it merged to v 9.0, but I will have a look at the tags you sent me. Thanks
