### ISSUE TITLE
Unable to "Enable Manage document pages (Wiki)"

### ISSUE THREAD

**Issue by buby84** [OCA/knowledge#132]
Hello, sorry i am pretty new so it c an be a stupid question, i am tring to install this module on my oddo 10 but when i try to check the "Manage document pages (Wiki)" and save i get redirtect to a page which say:

Odoo Warning - Warning
The one-click installation of Odoo Apps is currently unavailable. Please go to www.odoo.com/apps to download manually.

it look like it isntalling some module from store but functionality is been disabled,,, but i dont know which module is ..

what i can do?

**Comment by mquandalle** [comment]
Same problem here. Apparently we should be able to opt-in using

```
$ chmod +w /var/lib/odoo/.local/share/Odoo/addons/8.0/
```

but I still get the “The one-click installation of Odoo Apps is currently unavailable” message after that.

**Comment by pedrobaeza** [comment]
Closing as tri-aged
