### ISSUE TITLE
knowledge 10.0.1.0.0 does not get loaded under odoo 10.0 community edition

### ISSUE THREAD

**Issue by chrischmo** [OCA/knowledge#133]
Hi!

I'm currently checking out odoo 10.0 and have it running under Ubuntu Server 16.04. 
I tried to install your 'knowledge' module but had no success - these are my steps so far:

1. Downloaded the zip file for v10.0.1.0.0 from the app store, extracted it to [ODOO-DIR]/addons
2. Gave the resulting [ODOO-DIR]/addons/knowledge directory and its contents the same permissions as the odoo main directory (drwxr-xr-x odoo sudo) 
3. Started up the odoo server via `./odoo-bin -d demo`

The server showed no error messages during startup, but it stroke me as odd that the number of loaded modules remained unchanged. Then I went to 'Apps' -> 'Update Apps' in the UI, but the knowlegde module did not show up in the app list. I tried restarting the server, but the problems (number of loaded modules not incrementing and the module not showing up in my app list after updating it) remained.

Then I moved the knowledge directory from [ODOO-DIR]/addons to the parent folder of [ODOO-DIR] and tried to explicitly load it via `./odoo-bin -d demo --addons-path="../knowledge,./addons"`, but this resulted in an aborted server startup process with the error 

> odoo-bin: error: option --addons-path: The addons-path '../knowledge' does not seem to a be a valid Addons Directory!

Can you please help me?

Kind regards,

Christian

**Comment by max3903** [comment]
Hello @chrischmo

You need to activate the developer mode in Settings and then in Apps, update the module list.

**Comment by chrischmo** [comment]
Hello @max3903! Thank you for the tip, but I already did this (hence the 'Update Apps' part in my first post - Sorry, should have switched back odoo to English to get the exact menu entry instead of giving the German one).

But I found the solution [here](https://youtu.be/yaPv7i_2gCY?t=2m9s): You need to remove the default "Apps" filter in the app list search box - after doing this the module showed up and I could install it without problems.

Only out of curiosity and because a quick Google search did not turn up with anything useful: What makes an App an App and could you maybe explain why this module is not implemented as one (only if it's not too much of a hassle)?

Would it be OK to make a pull request that adds a corresponding hint to the description page? Because this might be trivial for experienced users but not for newbies like me.

**Comment by max3903** [comment]
@chrischmo 

The module manifest contains a key named `application` and the value can be true or false.

The `knowledge` module does not provide any feature, only configuration screen, user group, module category and menu items used by other modules in this repo. We don't expect this module to be searched and installed by the user. For example, the user should search and install the app Quality Management System (https://github.com/OCA/management-system/blob/9.0/mgmtsystem_quality/__openerp__.py#L37) and `knowledge` would be installed as a dependency.

Improving the documentation is more than OK. It is welcomed :)

**Comment by chrischmo** [comment]
@max3903, thank you for your explanation, that makes it clear. I'm currently a little tied up between work and uni, but will try to make the pull request during the weekend.

**Comment by dreispt** [comment]
Looks solved.
