### ISSUE TITLE
[9.0^][knowledge] Enterprise-like icon

### ISSUE THREAD

**Issue by ivantodorovich** [OCA/knowledge#151]
I've made an enterprise-like icon for this module.
What do you think?

**Please comment any suggestions regarding icon and/or color.**

1:
![knowledge_03](https://user-images.githubusercontent.com/1914185/34918869-028c3930-f939-11e7-944d-78039f662ddb.png)

2:
![knowledge_06](https://user-images.githubusercontent.com/1914185/34918958-a2bb19e8-f93a-11e7-8ab1-9eeee8c8082e.png)

Somehow related to https://github.com/OCA/management-system/issues/204

**Comment by leemannd** [comment]
@ivantodorovich It's a nice idea. I'm more for the second one because:
- It represent best knowlege
- I'm aready using the first one for a specific application developed for a school. So in my mind it represent more school/graduates management than a knowledge application. ;)

**Comment by pedrobaeza** [comment]
I also like 2. Can you use another color less dark?

**Comment by ivantodorovich** [comment]
Great, number 2 it is.

@pedrobaeza sure. I picked that color because it's the same color as the Notes app. Somehow thought it was good to have both apps on the same color.

Here are a few more options:

A:
![knowledge_03](https://user-images.githubusercontent.com/1914185/34951858-6aec8aee-f9f6-11e7-8ac4-25a35b210662.png)

B:
![knowledge_05](https://user-images.githubusercontent.com/1914185/34951859-6b0d7c2c-f9f6-11e7-92d7-3a6ec20b36d4.png)

C:
![knowledge_09](https://user-images.githubusercontent.com/1914185/34951861-6b315250-f9f6-11e7-84f0-bf636c7098dc.png)

D:
![knowledge_10](https://user-images.githubusercontent.com/1914185/34951863-6b51080c-f9f6-11e7-9e77-2ba13160bc8e.png)

E:
![knowledge2_03](https://user-images.githubusercontent.com/1914185/34951864-6b73cc16-f9f6-11e7-8f33-faf120699d0a.png)

F:
![knowledge2_05](https://user-images.githubusercontent.com/1914185/34951865-6b96291e-f9f6-11e7-8a60-294f2c465ed6.png)

G:
![knowledge2_09](https://user-images.githubusercontent.com/1914185/34951866-6bec1cde-f9f6-11e7-820f-3e6a628e1137.png)

H:
![knowledge2_10](https://user-images.githubusercontent.com/1914185/34951867-6c0e6096-f9f6-11e7-828f-081d5f999521.png)

**Comment by pedrobaeza** [comment]
Well, here I don't have special predilection...

**Comment by ivantodorovich** [comment]
Me neither. 
I'll make a PR using 2A, then.
