### ISSUE TITLE
11.0 Issue with menu?

### ISSUE THREAD

**Issue by gdgellatly** [OCA/knowledge#179]
![documents odoo](https://user-images.githubusercontent.com/5093264/42809287-613b7002-8a09-11e8-89b5-6cf2cb1bd0a6.png)

To my mind shouldn't pages be under document_root?  I'm not sure, I was just testing it and saw it is under the second documents menu.

**Comment by SalahAdDin** [comment]
@max3903 @gdgellatly I can confirm this problem today:
![deepin-screen-recorder_select area_20180906161228](https://user-images.githubusercontent.com/5034215/45159572-c8440080-b1ef-11e8-8b70-a7cda2cb6c6d.gif)

Can anyone help us with this?

**Comment by SalahAdDin** [comment]
**Update:**
I fixed this: https://github.com/OCA/knowledge/pull/184
@pedrobaeza can you review it, please?
