### ISSUE TITLE
[11.0][knowledge]Store attachments in an external DMS does not work

### ISSUE THREAD

**Issue by SalahAdDin** [OCA/knowledge#195]
Hi,

I'm looking this modules and I found a issue here:
![settingskboca](https://user-images.githubusercontent.com/5034215/49803914-4c170700-fd62-11e8-9dce-31add7e95cc0.png)
Clicking in both options does not trigger anything as far I can see.

Why?

**Comment by pedrobaeza** [comment]
Because that modules are not migrated, but the menus are there by default.
