### ISSUE TITLE
attachment_preview error

### ISSUE THREAD

**Issue by carlgrosser** [OCA/knowledge#203]
Error:
Uncaught Error: QWeb2: Template 'attachment_preview.AttachmentPreviewWidget' not found

Could add full log if needed. python-magic seems to be installed. Maybe I'm overlooking something.

**Comment by pedrobaeza** [comment]
Version? Please try on runbot (https://runbot.odoo-community.org/runbot/repo/github-com-oca-knowledge-118) to reproduce the problem.

**Comment by carlgrosser** [comment]
OMG, I'm sorry. Just needed a restart....
