### ISSUE TITLE
Knowledge does not show up in Menu

### ISSUE THREAD

**Issue by miguelsilvazup** [OCA/knowledge#216]
After having installed Knowledge, I cannot see it in Odoo 12 menu. How to track this? I am not an advanced user.

**Comment by pedrobaeza** [comment]
Try to reproduce the problem on runbot. The link to runbot is on README.

**Comment by miguelsilvazup** [comment]
I cannot, because Knowledge is already functioning in Runbot. There I can see Knowledge in the Menu, but at my Odoo I can't. But I will try again.
