### ISSUE TITLE
You try to install module 'document_page_approval' that depends on module 'email_template'. But the latter module is not available in your system.

### ISSUE THREAD

**Issue by godinperson** [OCA/knowledge#220]
When I try to install Document Page approval, it gives me that error: 
You try to install module 'document_page_approval' that depends on module 'email_template'.
But the latter module is not available in your system.

Odoo 12, Community Edition

Thanks

**Comment by pedrobaeza** [comment]
You don't have the proper addon included in your path, as the manifest clearly states the dependencies, and it's not that one:

https://github.com/OCA/knowledge/blob/169eebd7f6c8aabc1c87e5037a4292b5351e34e0/document_page_approval/__manifest__.py#L13

**Comment by diassynthesis** [comment]
For odoo 12 you don't need the [email_template](https://github.com/buguelos/odoo/tree/master/addons/email_template) module.
So you are probably trying to install the wrong version of document_page_approval!!!
For v12 download the right version [https://github.com/OCA/knowledge/tree/12.0/document_page_approval](url)

**Comment by godinperson** [comment]
It's the right version because when I open the manifest, I clearly see mail instead of email_template. I'll check tomorrow. Also, the full quality module are available for v12?

**Comment by diassynthesis** [comment]
document_page_approval depends on email_template for V7.0 and V8.0 only.
What's wrong ?

**Comment by godinperson** [comment]
Works this morning. Looks like it was a cache issue.

Thanks guys!
