### ISSUE TITLE
Problem installing Knowledge addon on odoo 10

### ISSUE THREAD

**Issue by ofrmax** [OCA/knowledge#226]
Hi, I'm trying to instal the knowledge plugin on my odoo 10 but I'm facing a problem during the configuration. I have been able to install the plugin but when I click on the knowledge icon it brings me on the configuration of the plugin. As soon as I click on the apply button odoo bring me back to the main page. When I click again on knowledge it still brings me to the configuration page. Any idea why? Is there any other addon I need to install?

you can see my odoo version here 

![image](https://user-images.githubusercontent.com/19998638/68155191-303ac780-ff17-11e9-99b1-168e80865bb6.png)

here is the configuration screen I see when I click on the knowledge icon:

![image](https://user-images.githubusercontent.com/19998638/68155334-814abb80-ff17-11e9-9d35-8a5009e5d8b5.png)

**Comment by pedrobaeza** [comment]
There's no more on that module. Install extra modules like `document_page` for having other menus.
