### ISSUE TITLE
document_page and document_page_approval porting

### ISSUE THREAD

**Issue by gborelli** [OCA/knowledge#23]
I'm interested in porting these packages to Odoo 8.0 

I saw somebody alerady ported _document_page_ to 8.0 in this fork - https://github.com/savoirfairelinux/knowledge/tree/8.0-document-page

_document_page_ is dependency of these packages:
- _document_page_approval_
- _document_page_multi_company_

I suggested a pull request to the author of the porting that will help to migrate these modules
- https://github.com/savoirfairelinux/knowledge/commit/8d97a7ba0192c2c8cf3b3aba9dc8fbae8d96a6db

**Comment by bwrsandman** [comment]
Hi @gborelli, the commit you mentioned only fixes code style, it is not a port to 8.0.
document_page is not yet ported to 8.0, that work needs to be done first

**Comment by gborelli** [comment]
I tried that fork of document_page on odoo 8 yesterdary and it works.

@bwrsandman  would you mind to explain me what do you mean with 'porting'?
Do it means using new API or is it enough that a package works with Odoo 8.0?

btw: I'm going to fork this repository -  https://github.com/OCA/knowledge/ - to port it to odoo 8 and to add _document_page_, if you agree

**Comment by pedrobaeza** [comment]
Hi, Giorgio, migrating to new API is not mandatory, although it is better if you want to do it (shorter code, more possibilities, and a simpler migration to future v9).

Waiting for the PR then! :wink: 

Thanks

**Comment by bwrsandman** [comment]
@gborelli If it works, that's great, you're free to open a pull request, even with the code you referenced.

Porting usually involves firstly, making sure the code works, and using the new API of 8.0.

There will be an automatic test by travis and a review on that code by OCA reviewers. They will point out any possible problems and further assist you.

**Comment by gborelli** [comment]
document_page pull request - https://github.com/OCA/knowledge/pull/24

**Comment by gborelli** [comment]
document_page_approval pull request - https://github.com/OCA/knowledge/issues/25
