### ISSUE TITLE
[RFC] Wiki Roadmap

### ISSUE THREAD

**Issue by max3903** [OCA/knowledge#252]
# 1.0.0

#249 installed on https://en.odoodoc.org
#250 
#251

# 1.1.0

* Page: Provide a table of content at the top of each page
* Menu: Display the tree structure of tags (instead of a flat list)
* Edition: Easy selection of wiki pages when creating internal link
* Search: Allow mixing category and multiple tags

# 1.2.0

* ???

**Comment by bjoliveau** [comment]
HI @max3903 
Maybe you plan anchor in page with "Provide a table", either not, it should be nice to add anchor feature in the same page.
