### ISSUE TITLE
[12.0] document_page_reference: iframe youtube video missing from rendering

### ISSUE THREAD

**Issue by ypapouin** [OCA/knowledge#266]
@etobella, I didn't take a look on this module code but when you install it, pages that contains links to Youtube videos are not rendered correctly since the iframe tag is no more added to the readonly view.

**Comment by ypapouin** [comment]
Ok , I found why, content_parsed is an Html field, it should be a Text one to avoid sanitizing.
Preparing a MR

**Comment by flotho** [comment]
this one could be closed if the PR is merged ?
