### ISSUE TITLE
[FIX] document_page_approval: Remove diff in mail

### ISSUE THREAD

**Issue by victoralmau** [OCA/knowledge#274]
When a page related to a category that needs approval is created or edited, an email with information from the record `document_page_history` that has been created is sent to the user of the approval group.

I think that `${object.diff | safe}` in the email should be removed by different arguments:

- If the changes contain html (it is quite common) the review by email becomes "impossible".
- If there are images inserted in html and / or videos in the content of the page, when trying to send the email, odoo tries to auto-create an attachment (`ir_attachment`) with an impossible type (type = content); that is, an error appears.

What do you think about it?

Ping @max3903

**Comment by pedrobaeza** [comment]
OK for me. I'm not only that reasons, but "digital ecology": sending all that content by mail is a great byte waste.

**Comment by bjoliveau** [comment]
+1

**Comment by flotho** [comment]
@victoralmau any PR associated to this ?

**Comment by pedrobaeza** [comment]
Done in #292
