### ISSUE TITLE
 No field to add url is seen

### ISSUE THREAD

**Issue by jaimeramva** [OCA/knowledge#305]
module: document_url
version: 13.0

Hello I have installed the module in version 13 but it does not let me see the add url or the wizard to be able to do it, what do I need to activate?

![image](https://user-images.githubusercontent.com/17528457/136437005-ce9dd06e-45b8-4335-bcec-65b2372c3e40.png)

**Comment by pedrobaeza** [comment]
Please follow the link on the README called "Runbot | Try me" and test if it's working there. If it's, then it seems you haven't installed properly the module.
