### ISSUE TITLE
[V16] knowledge is back

### ISSUE THREAD

**Issue by legalsylvain** [OCA/knowledge#316]
For your information, Odoo is reintroducing a module named ``knowledge`` here

https://github.com/odoo/odoo/pull/81158

Don't know if it cover the same scope as before in V8 (https://github.com/odoo/odoo/tree/8.0/addons/knowledge)
but it will requires some adaptation with the current V15 OCA module. 

kind regards.

**Comment by marcelsavegnago** [comment]
Starting with the name change :D knowledge_oca

**Comment by HaraldPanten** [comment]
THX for reporting!

**Comment by pedrobaeza** [comment]
It has been merged: https://github.com/odoo/odoo/commit/42a3b704f7c7889a74338253138d0201d3b6e7a3

**Comment by rafaelbn** [comment]
It looks more like Notion than v8 version ❤️ 

![image_225c59e3-a924-426b-ab01-eec9d9df906d20220513_142619](https://user-images.githubusercontent.com/8736623/168321291-d453ad66-46e9-4dfa-ba0d-1f9463f50082.jpg)
