### ISSUE TITLE
Open Question regarding Knowledge and DMS

### ISSUE THREAD

**Issue by flotho** [OCA/knowledge#317]
Hi,

I woulld like to know if OCA/Knowledge and OCA/DMS and probably OCA/Storage could have some duplicate functions ?
As far AS I can See the DMS module is really awesome for managing document and Konwledge is not so efficient on this part
Won't it be a good Idea to use DMS when checking here : https://github.com/OCA/knowledge/blob/13.0/knowledge/models/res_config.py#L16

Maybe more bridges could be achieved between those repos

Thanks for your feedback

**Comment by pedrobaeza** [comment]
`knowledge` module per se does nothing. The most valuable module belonging to that category is `document_page`. That one vs DMS differences are:

- document_page is for texts - and more important, for texts included in own Odoo - visualization and edition.
- DMS is for files, of any kind, and with no easy visualization of texts right now (and obviously not edition).

I don't know storage.

**Comment by flotho** [comment]
Thanks for this confirmation,
So my idea is to propose to replace/imporve the behaviour of this option https://github.com/OCA/knowledge/blob/13.0/knowledge/models/res_config.py#L16 to install DMS
Would it make sense to you I I propose a PR on this direction ?

**Comment by pedrobaeza** [comment]
No, in fact, I would remove such options. They are very wrong. They make sense when the full pack is provided, like in Odoo S.A., but in a module per module migration, to provide an empty module that installs other modules that are not yet migrated (or that they ever won't be migrated), is not correct.

**Comment by flotho** [comment]
Sorry to reformulate,

if I understand you correctly :
* My proposal make no sense regarding the fact that both repo are independent and mostly not available in the same versions 
* You even suggest to delete the option to manage document in this knowledge module in order to be more consistent

Am I right ?

**Comment by pedrobaeza** [comment]
Yes, but in general I consider that there shouldn't be any kind of such res.config.settings entries for installing other modules inside OCA, being from the same repository or from others. In fact, I hate this feature in general from Odoo, as users click everywhere on the settings without advertising that they are installing modules. Maybe it's done on purpose by Odoo?

**Comment by flotho** [comment]
huummm I understand,
So if I propose a PR for deleting the actual behaviour of knowledge module the add only groups and menu will it make sense to you ?

**Comment by pedrobaeza** [comment]
Other users appreciate such feature, like @max3903, but I will accept to not have them.

**Comment by flotho** [comment]
IMHO this is a great feature but the DMS module in v12 and more is much more efficient .
Adding a tip in the res config view to explain that DMS repo is a better solution could help.
Could it be Ok for you and @max3903

**Comment by pedrobaeza** [comment]
I prefer to have all of those explanations on the modules READMEs, not polluting setting screens.
