### ISSUE TITLE
[14.0] document_url: Error when activating 'Dev mode with assets'

### ISSUE THREAD

**Issue by MiquelRForgeFlow** [OCA/knowledge#322]
## document_url
Module with the bug.

## Bug

![image](https://user-images.githubusercontent.com/25005517/149978643-13c5599b-cb4b-427f-acbd-6999076721a2.png)

![Selection_157](https://user-images.githubusercontent.com/25005517/149978614-002aee30-fde7-4f3a-bf01-354c06aec793.png)

## To Reproduce
**Affected versions**: 14.0

Go to settings, and active 'Dev mode with assets'
![Selection_158](https://user-images.githubusercontent.com/25005517/149978367-d2970803-290c-42f0-a873-b6a4ae1e9a1c.png)

**Expected behavior**
No bug.

**Additional context**
I don't know.

**Comment by victoralmau** [comment]
Hi Miquel, thanks for explaining about the error.
I have created https://github.com/OCA/knowledge/pull/323 to solve it, can you check it?
