### ISSUE TITLE
document_page_print_multi

### ISSUE THREAD

**Issue by max3903** [OCA/knowledge#38]
This module allows you to create a wiki page with the table of content (ordered list of links to other pages) and allow the user to print a PDF with the concatenation of the toc and the pages content (including images, see #39).

**Comment by pedrobaeza** [comment]
Is this still relevant?

**Comment by etobella** [comment]
Is this still relevant? @max3903

**Comment by bjoliveau** [comment]
Tested today on V12 CE and okay to print several pages from view list to only one pdf report.
This issue may be closed.
