### ISSUE TITLE
document_page_file

### ISSUE THREAD

**Issue by max3903** [OCA/knowledge#39]
This module allows you to include attached files in a document page. If the file is an image (jpg or png), the image is displayed within the page.

**Comment by hbrunn** [comment]
just for reference: If you install web_ckeditor, you can do this because it embeds an uploaded file as data uri. But creating an attachment on the fly would be better of course

**Comment by pedrobaeza** [comment]
Is this still relevant?

**Comment by etobella** [comment]
Is this still relevant? @max3903

**Comment by max3903** [comment]
Yes

**Comment by etobella** [comment]
Ok, are you going to propose some kind of module then?

**Comment by max3903** [comment]
Not right now...
