### ISSUE TITLE
[16.0] attachment_zipped_download: Incomplete file

### ISSUE THREAD

**Issue by DarioLodeiros** [OCA/knowledge#406]
Failed to open the downloaded zips

## Module
attachment_zipped_download

## Describe the bug
Go to Settings > Technical > Database Structure > Attachments and select some files. Then download files and we can see the error in the downloaded file:
![image](https://user-images.githubusercontent.com/11718836/224478012-4f7daf3c-08e8-4dad-821d-19b98f18b056.png)

## To Reproduce
Tested in runbot 16.0, in 14.0 this run fine.

https://user-images.githubusercontent.com/11718836/224478304-59a1c32c-d3f0-4812-9ada-85075f830c66.mp4

**Expected behavior**

**Additional context**
Tested in Brave 1.48, Chrome 110.0.5481 and Firefox 110.01

**Comment by pedrobaeza** [comment]
Can you try in local? Currently the runboat certificate is expired, so it can be the reason.

**Comment by pedrobaeza** [comment]
@sbidoul can you check the certificate part?

**Comment by DarioLodeiros** [comment]
Sorry, I am left without notifying the response, but yes, indeed I first detected it locally, and then I checked it in runbot.
I understand that it is some change in the library that is used in pyhon??,

**Comment by pedrobaeza** [comment]
I can't say. In previous tests, it was working.

**Comment by len-foss** [comment]
@pedrobaeza 
It seems it's an issue with Werkzeug's dealing with the BytesIO object.
Adding `fo = tempfile.NamedTemporaryFile(); fo.write(out_file.getvalue())` and passing the filename `fo.name` as argument to send_file works as expected. 

In all other cases, it sends the correct size in the headers, but it does not actually stream the file. Not sure what might have changed between versions.

**Comment by pedrobaeza** [comment]
Thanks for the investigation! Can you do a PR doing that changes?

**Comment by len-foss** [comment]
Should be good now :-)
