### ISSUE TITLE
Document_URL not available

### ISSUE THREAD

**Issue by PaulGoubert** [OCA/knowledge#413]
## Module
Document_URL : https://github.com/OCA/knowledge/tree/16.0/document_url

## Describe the bug
Cannot find the feature.   Didn't see the wizard once we click on paper clip. 

## To Reproduce
**Affected versions**: launch a runbot and try to use document_url module

Open the form view of an object (Example: Customer Invoice INV/2019/0007).
Go to the chatter and click on the attached icon.
"Click Add URL link."   Their is not "Add URL Link" 

**Expected behavior**
Open the form view of an object (Example: Customer Invoice INV/2019/0007).
Go to the chatter and click on the attached icon.
Click Add URL link.
Fill the wizard fields and click on Add button.
You will see a new URL attachment in the set of attachments related to the object.

**Additional context**
V16

**Comment by PaulGoubert** [comment]
@victoralmau @matiasperalta1 @FernandoRomera

**Comment by pedrobaeza** [comment]
It's true that is not working. On 16.0, now clicking on the clip icon if no attachments, leads directly to the select file wizard instead of unfolding the attachments section, but even if you add an attachment, the "Add URL" link is not appearing.

cc @etobella

**Comment by bealdav** [comment]
Thanks @pedrobaeza to have confirmed it

**Comment by bealdav** [comment]
@etobella what do you think on this topic ?

**Comment by etobella** [comment]
I do not use (and never looked on) document_url :upside_down_face: 

After checking on runboat, it seems that the behaviour of the attachment button has changed from 15 to 16 if no attachments are defined. We probably need to modify it.

Also, once we we have an attachment and we press on it, we cannot see the url attachment button.

Someone need to do a PR fixing it. If you are unable to propose one, I can check it on the Spanish OCA Days

**Comment by bealdav** [comment]
Thanks a lot @etobella, if you may propose to solve this issue on the spanish OCA days, it could be great.

Thanks a lot.

**Comment by PaulGoubert** [comment]
Hello everybody.    Thank you @etobella , @pedrobaeza  and @bealdav for your reply.    
It could be very cool if this issue can be solved during the next OCA days. 
My customer want to link some huge documents and start to do it as attached files.  We advise him to store those documents somewhere else in the cloud, and use a link in Odoo as attachement.    

Thank you all.

**Comment by pedrobaeza** [comment]
You can fund any of the contributors to do the fix. Meanwhile, there's no guarantee of deadlines for this.
