### ISSUE TITLE
Project Integration

### ISSUE THREAD

**Issue by flt-papillo** [OCA/knowledge#433]
As for now i could not find any opportunity to link projects to knowledge pages.

I wonder, because is it not a obvious feature if you offer different services you can link a knowledge space to the project for documentation reasons? 

In Documents model it is already integrated, so for every project there is a space to leave some docs there. Why not for projects?

**Comment by gjotten** [comment]
See https://github.com/OCA/knowledge/pull/464 where in 16.0 we are adding the project link in on document records again, as well as a link on projects to show all documents.
