### ISSUE TITLE
[14.0] document_url incompatible with some addons -- in particular google_drive_odoo (non-free)

### ISSUE THREAD

**Issue by whotopia** [OCA/knowledge#435]
The document_url addon, if installed at the same time as the addon google_drive_odoo (from faotools) causes all kinds of havoc and doesn't work. (needs to be uninstalled via the database as UI unusable).  

Is there anything that can be done to make document_url less conspicuous and still work with the faotools addon installed?  ( google_drive_odoo and its dependency cloud_base) ?

**Comment by pedrobaeza** [comment]
The module is built following standards, so probably the "bad guy" here is the other non-OCA module. Anyway, this is not something that should be handled at OCA level, so closing.
