### ISSUE TITLE
[16.0] Document Page html widget 0 size

### ISSUE THREAD

**Issue by iangozer** [OCA/knowledge#452]
When installing Document Page addon the "Content" HTML widget is so small even a single character has scroll bars

## Module
Document Page

## Describe the bug
When installing Document Page addon the "Content" HTML widget is so small even a single character has scroll bars

## To Reproduce
**Affected versions**: 
document_knowledge-16.0.1.1.0
Document Page_16_0_221220_064521

Basic install, no settings required

**Expected behavior**
Should be full width

**Additional context**
Changing...
`<group>
    <div>
        <field name="content" widget="html" placeholder="e.g. Once upon a time..." required="1" options="{'safe': True, 'codeview': True}"/>
        </div>
</group>`
to ...
`<field name="content" widget="html" placeholder="e.g. Once upon a time..." required="1" options="{'safe': True, 'codeview': True}"/>`
produces the expected result.

**Comment by lorenzomorandini** [comment]
Same problem here.

EDIT: Installing the latest version from this repo fixes it
