### ISSUE TITLE
Can you have a plan to upgrade attachment_preview for Odoo 17?

### ISSUE THREAD

**Issue by manhkv** [OCA/knowledge#495]
Can you have a plan to upgrade attachment_preview for Odoo 17

![image](https://github.com/user-attachments/assets/3f268ebb-ba84-402d-9a83-2e7bbf3dddce)

**Comment by pedrobaeza** [comment]
No plans, as this is open source. You can fund any of the authors/contributors of the module (or anyone else) to migrate it, or migrate it by yourself.
