### ISSUE TITLE
[16.0][BUG] Page Title truncated in Page Viewing mode

### ISSUE THREAD

**Issue by peterromao** [OCA/knowledge#497]
When viewing the final aspect of a page the title gets cut short as the field to show it is too short. See runboat image below:

![image](https://github.com/user-attachments/assets/c358146c-6d5a-4b34-97a5-6656c72b33a4)

## Module
document_page

## Describe the bug
The view has the field defined as:
```
<div class="oe_title">
    <h1>
        <field name="name" placeholder="Name" />
    </h1>
</div
``` 

## To Reproduce
**Affected versions**: 16.0

1. Create a menu for a category
2. Go to said menu
3. Open a page with a long title

**Expected behavior**
The Title field should adjust to the size of the text or at least give enough clearente fo rlonger titles

Thanks

**Comment by pedrobaeza** [comment]
This was just fixed in #494 

Update your code.
