### ISSUE TITLE
"Run me on runbot" link is broken 

### ISSUE THREAD

**Issue by amicalmant** [OCA/knowledge#86]
module: document_page_approval
version: 9.0

**Steps to reproduce**
- Browse to: https://github.com/OCA/knowledge/tree/9.0/document_page_approval
- Click on the "Run me on runbot" link:

**Current behavior**
The link is broken.

**Expected behavior**
We should be able to run the module demo, shouldn't we?

**Comment by max3903** [comment]
@amicalmant Yes, we should. I am working on it.

**Comment by max3903** [comment]
Maybe due to https://github.com/OCA/OCB/issues/432

**Comment by Garamotte** [comment]
This seems to be caused by the removal of the `/login` route : https://github.com/odoo/odoo/commit/afa9f4b

**Comment by Garamotte** [comment]
The same issue exists on the official Odoo runbot : http://runbot.odoo.com/runbot/1/9.0
The `/login` route still exists on 8.0, and it works : http://runbot.odoo.com/runbot/1/8.0

Runbot was not adapted to this change :
https://github.com/odoo/odoo-extra/blob/d0b43dea1658432290f89878ed82164e2fe893f9/runbot/runbot.py#L1529

**Comment by amicalmant** [comment]
En ce cas-là, à votre place, je supprimerai cette ressource de la page Web
car cela fait un peu désordre:

> > The requested URL was not found on the server. If you entered the URL
> > manually please check your spelling and try again.

---

Christian Aubry | COMMUNICATEUR NUMÉRIQUE
Communication Web, gestion de contenu, médias sociaux,
reportage, entrevue, captation vidéo et webdiffusion
www.aubry.org http://christian.aubry.org/ | christian@aubry.org |

## +1-514-501-9368

[image: YouTube] http://youtube.com/user/amicalmant   [image: LinkedIn]
http://ca.linkedin.com/in/christianaubry   [image: Twitter]
http://twitter.com/amicalmant   [image: Facebook]
http://www.facebook.com/christian.aubry   [image: Delicious]
http://delicious.com/amicalmant   [image: Flickr]
http://www.flickr.com/photos/amicalmant/  [image: Skype]▸amicalmant

2016-03-25 16:10 GMT-04:00 max3903 notifications@github.com:

**Comment by gurneyalex** [comment]
See https://github.com/odoo/odoo-extra/issues/103

**Comment by gurneyalex** [comment]
issue fixed on our runbot instance.
