### ISSUE TITLE
[9.0] document_approval

### ISSUE THREAD

**Issue by max3903** [OCA/knowledge#88]
# Document Approval

This module adds a workflow to approve new document revisions and download the last approved
one by default.
## Installation
- No installation required
## Configuration

To configure this module, you need to:
- set a valid email address on the company settings
- go to Knowledge > Directories
- select a directory
- check the `Requires approval` checkbox
- set the approving groups and their sequence. Make sure users belonging to those groups have valid email addresses.
## Usage

To use this module, you need to:
- go to Knowledge > Documents
- create and upload a new document and choose the previously created category. A notification is sent to the group with the document revision to review as an attachment.
- based on the review, the document revision is approved or not.
- users downloading the document get the latest approved revision.
# Multi-level Approval
## Parallel approval:

Configuration:
- Group 1 and sequence = 1 
- Group 2 and sequence = 1

Process: 
- An email is sent to users of Group 1 and Group 2.
- The first user belonging to Group 1 or Group 2 approves.
- Document is approved
## Sequential approval

Configuration:
- Group 1 and sequence = 1 
- Group 2 and sequence = 2

Process:
- An email is sent to users of Group 1
- The first user belonging to Group 1 approves.
- An email is sent to users of Group 2
- The first user belonging to Group 2 approves.
- Document is approved

**Comment by max3903** [comment]
Depends on:
- [ ] document_revision (#87)

**Comment by dreispt** [comment]
I think Odoo sequences usually begin on 1.

**Comment by max3903** [comment]
<script type="text/javascript" src="https://mobbr.com/mobbr-button.js"></script>
<script type="text/javascript">
                                mobbr.button('https://github.com/OCA/knowledge/issues/88', 'EUR', 'large');
                                </script>

**Comment by pedrobaeza** [comment]
Is this still relevant?
