### ISSUE TITLE
Error of maximum recursion in category 

### ISSUE THREAD

**Issue by luistorresm** [OCA/knowledge#93]
1) Steps to reproduce the issue you have observed

1.- Create a new Category with the next values:
name = 'OpenERP Features'

2.- Save the Category, and edit to set the parent_id = Category created in step 1
![category odoo](https://cloud.githubusercontent.com/assets/7606656/15792095/b3c7335e-29a0-11e6-84ab-fc61a2d6807a.png)

2) The result you observed
When I save get `RuntimeError: maximum recursion depth exceeded while calling a Python object`

![category odoo](https://cloud.githubusercontent.com/assets/7606656/15792128/f086e3de-29a0-11e6-84eb-08060bf609f0.png)

 3) The result you expected
I can not select the same category as parent.

 4) The Odoo version 
8.0 46811e3e5a49c00ef25c04a92b41d2ae27a99c7b

**Comment by max3903** [comment]
@Luistorresm Thanks for reporting.  I will check this next week.

**Comment by luistorresm** [comment]
Hello @max3903 

You've had an opportunity to review this issue?

Regards

**Comment by max3903** [comment]
@luistorresm Not yet. Probably next week.

**Comment by pedrobaeza** [comment]
Is this problem still there?

**Comment by max3903** [comment]
Thanks for the reminder.

I have been dragged by a last minute training. I will do my best to answer
this week.

Cheers,

Maxime Chambreuil

**Comment by max3903** [comment]
@luistorresm The parent category needs to be different from the current category. Choose another category and it will work.

**Comment by luistorresm** [comment]
Yes @max3903 

But I think that the system must not allow use the same category as parent, to avoid the traceback.

What do you think?

Regards

**Comment by max3903** [comment]
@luistorresm I think we need to check that constraint on update. Do you have time to do it?

**Comment by nicomacr** [comment]
I've fix this problem in 11.0  #202
