### ISSUE TITLE
[9.0]  document_url  AddUrlDocumentItem' not found

### ISSUE THREAD

**Issue by lucode** [OCA/knowledge#98]
After installing the module I get the following error whenever I try to go on a list menue:

`Error: QWeb2: Template 'AddUrlDocumentItem' not found`
[error.log.txt](https://github.com/OCA/knowledge/files/418074/error.log.txt)

It could be that the error is caused  by using the United Backend theme? Unfortunately I can't uninstall none of the modules so far.

**Comment by pedrobaeza** [comment]
Try to restart server and refresh browser.

**Comment by lucode** [comment]
thanks @pedrobaeza  that did help. The Backend end theme did not hurt.
